server:
  baseUrl:
    $env: APP_URL
  port: 5000
  apiKey:
    $env: API_KEY
  schemaPath: /open-api.json
  apiBasePath:
    $env: AGENT_ENDPOINT
  apiDocsPath: /api-docs
  defaultIdentity:
    create: false
  exposedMethods:
    - keyManagerGetKeyManagementSystems
    - keyManagerCreateKey
    - keyManagerGetKey
    - keyManagerDeleteKey
    - keyManagerImportKey
    - keyManagerEncryptJWE
    - keyManagerDecryptJWE
    - keyManagerSignJWT
    - keyManagerSignEthTX
constants:
  secretKey:
    $env: SECRET_KEY
dbConnection:
  $require: typeorm?t=function#createConnection
  $args:
    - type: postgres
      url:
        $env: DATABASE_URL
      synchronize: true
      logging: false
      entities:
        $require: daf-typeorm?t=object#Entities
agent:
  $require: daf-core#Agent
  $args:
    - plugins:
        - $require: daf-key-manager#KeyManager
          $args:
            - store:
                $require: daf-typeorm#KeyStore
                $args:
                  - $ref: /dbConnection
                  - $require: daf-libsodium#SecretBox
                    $args:
                      - $ref: /constants/secretKey
              kms:
                local:
                  $require: daf-libsodium#KeyManagementSystem
