server:
  baseUrl: http://localhost:3332
  port: 3332
  # apiKey: foobar
  schemaPath: /open-api.json
  apiBasePath: /agent
  apiDocsPath: /api-docs
  defaultIdentity:
    create: false
  ngrok:
    connect: true
  #   subdomain: none
  #   region: eu
  # authtoken:
  exposedMethods:
    - keyManagerGetKeyManagementSystems
    - keyManagerCreateKey
    - keyManagerGetKey
    - keyManagerDeleteKey
    - keyManagerImportKey
    - keyManagerEncryptJWE
    - keyManagerDecryptJWE
    - keyManagerSignJWT
    - keyManagerSignEthTX
constants:
  secretKey: 29739248cad1bd1a0fc4d9b75cd4d2990de535baf5caadfdf8d8f86664aa830c
  databaseFile: ./db/database.sqlite
dbConnection:
  $require: typeorm?t=function#createConnection
  $args:
    - type: sqlite
      database:
        $ref: /constants/databaseFile
      synchronize: true
      logging: false
      entities:
        $require: daf-typeorm?t=object#Entities
agent:
  $require: daf-core#Agent
  $args:
    - plugins:
        - $require: daf-key-manager#KeyManager
          $args:
            - store:
                $require: daf-typeorm#KeyStore
                $args:
                  - $ref: /dbConnection
                  - $require: daf-libsodium#SecretBox
                    $args:
                      - $ref: /constants/secretKey
              kms:
                local:
                  $require: daf-libsodium#KeyManagementSystem
